use crate::reporter::types::ScanReport;
use std::fs::File;
use std::io::Write;
use std::path::Path;
use thiserror::Error;
use tracing::info;

#[derive(Error, Debug)]
pub enum MarkdownReportError {
    #[error("IO error: {0}")]
    Io(#[from] std::io::Error),
}

pub struct MarkdownReporter;

impl MarkdownReporter {
    pub fn generate(report: &ScanReport, output_path: &Path) -> Result<(), MarkdownReportError> {
        let mut file = File::create(output_path)?;

        writeln!(file, "# Xikomap Security Scan Report")?;
        writeln!(file)?;
        writeln!(file, "## Executive Summary")?;
        writeln!(file)?;
        writeln!(file, "- **Target:** `{}`", report.target)?;
        writeln!(file, "- **Scan Date:** {}", report.timestamp.format("%Y-%m-%d %H:%M:%S"))?;
        writeln!(file, "- **Total Ports Scanned:** {}", report.total_ports_scanned)?;
        writeln!(file, "- **Open Ports Found:** {}", report.open_ports)?;
        writeln!(file, "- **Scan Duration:** {:.2} seconds", report.scan_duration_secs)?;
        writeln!(file)?;

        writeln!(file, "## Scan Configuration")?;
        writeln!(file)?;
        writeln!(file, "- **Scanner Version:** {}", report.metadata.version)?;
        writeln!(file, "- **Concurrency:** {}", report.metadata.concurrency)?;
        writeln!(file, "- **Timeout:** {}ms", report.metadata.timeout_ms)?;
        writeln!(file, "- **Max Retries:** {}", report.metadata.retries)?;
        writeln!(file)?;

        if !report.results.is_empty() {
            writeln!(file, "## Open Ports")?;
            writeln!(file)?;
            writeln!(file, "| IP Address | Port | Protocol | Service/Banner |")?;
            writeln!(file, "|------------|------|----------|------------------|")?;

            for res in &report.results {
                let banner_escaped = res.banner.replace("|", "\\|");
                writeln!(
                    file,
                    "| {} | {} | {} | `{}` |",
                    res.ip, res.port, res.protocol, banner_escaped
                )?;
            }
            writeln!(file)?;
        }

        writeln!(file, "---")?;
        writeln!(file, "*Generated by Xikomap v{}*", report.metadata.version)?;

        info!("Markdown report saved to: {}", output_path.display());
        Ok(())
    }
}