use crate::core::graph::{GraphNode, ReconGraph};
use printpdf::{BuiltinFont, Mm, PdfDocument};
use std::fs::File;
use std::io::BufWriter;

pub struct PdfReporter;

impl PdfReporter {
    pub fn generate(
        graph: &ReconGraph,
        target: &str,
        output_path: &str,
    ) -> Result<(), Box<dyn std::error::Error>> {
        let (doc, page1, layer1) = PdfDocument::new(
            &format!("xikomap Report - {}", target),
            Mm(210.0),
            Mm(297.0),
            "Layer 1",
        );
        let current_layer = doc.get_page(page1).get_layer(layer1);

        let font = doc.add_builtin_font(BuiltinFont::HelveticaBold)?;
        let font_normal = doc.add_builtin_font(BuiltinFont::Helvetica)?;

        current_layer.use_text("xikomap Reconnaissance Report", 24.0, Mm(10.0), Mm(280.0), &font);
        current_layer.use_text(
            &format!("Target: {}", target),
            14.0,
            Mm(10.0),
            Mm(265.0),
            &font_normal,
        );
        current_layer.use_text(
            &format!(
                "Scan Date: {}",
                chrono::Local::now().format("%Y-%m-%d %H:%M:%S")
            ),
            12.0,
            Mm(10.0),
            Mm(255.0),
            &font_normal,
        );
        current_layer.use_text(
            &format!("Total Nodes: {}", graph.node_count()),
            12.0,
            Mm(10.0),
            Mm(245.0),
            &font_normal,
        );
        current_layer.use_text(
            &format!("Total Edges: {}", graph.edge_count()),
            12.0,
            Mm(10.0),
            Mm(235.0),
            &font_normal,
        );

        let mut y_position = 215.0;

        current_layer.use_text("Open Ports", 16.0, Mm(10.0), Mm(y_position), &font);
        y_position -= 10.0;

        let mut port_count = 0;
        for node in graph.nodes() {
            if let GraphNode::Port { port, .. } = node {
                if y_position < 20.0 {
                    break;
                }
                current_layer.use_text(
                    &format!("  Port: {}", port),
                    11.0,
                    Mm(15.0),
                    Mm(y_position),
                    &font_normal,
                );
                y_position -= 6.0;
                port_count += 1;
            }
        }

        if port_count == 0 {
            current_layer.use_text(
                "  No open ports detected",
                11.0,
                Mm(15.0),
                Mm(y_position),
                &font_normal,
            );
            y_position -= 6.0;
        }

        y_position -= 10.0;
        if y_position > 40.0 {
            current_layer.use_text("Detected Services", 16.0, Mm(10.0), Mm(y_position), &font);
            y_position -= 10.0;

            for node in graph.nodes() {
                if let GraphNode::Service { name, port } = node {
                    if y_position < 20.0 {
                        break;
                    }
                    current_layer.use_text(
                        &format!("  {} on port {}", name, port),
                        11.0,
                        Mm(15.0),
                        Mm(y_position),
                        &font_normal,
                    );
                    y_position -= 6.0;
                }
            }
        }

        y_position -= 10.0;
        if y_position > 40.0 {
            current_layer.use_text("Technologies", 16.0, Mm(10.0), Mm(y_position), &font);
            y_position -= 10.0;

            for node in graph.nodes() {
                if let GraphNode::Technology { name, version } = node {
                    if y_position < 20.0 {
                        break;
                    }
                    current_layer.use_text(
                        &format!("  {} ({})", name, version),
                        11.0,
                        Mm(15.0),
                        Mm(y_position),
                        &font_normal,
                    );
                    y_position -= 6.0;
                }
            }
        }

        current_layer.use_text(
            "Generated by xikomap - https://github.com/yoxiko/xikomap",
            9.0,
            Mm(10.0),
            Mm(15.0),
            &font_normal,
        );

        doc.save(&mut BufWriter::new(File::create(output_path)?))?;
        Ok(())
    }
}