import re
import json
from typing import Dict, List, Optional, Tuple, Set
from urllib.parse import urljoin
import requests
from bs4 import BeautifulSoup

class CMSFrameworkDetector:

    def __init__(self, timeout: float = 5.0):
        self.timeout = timeout
        self.detection_cache = {}
        
        self.cms_patterns = {
            'WordPress': {
                'html_patterns': [
                    r'wp-content', r'wp-includes', r'wp-json', r'wordpress',
                    r'/wp-admin/', r'wp-embed', r'wp-block', r'wp-caption'
                ],
                'meta_patterns': [
                    r'<meta name="generator" content="WordPress',
                    r'generated by wordpress'
                ],
                'header_patterns': [
                    r'x-wp-', r'wp-'
                ],
                'file_patterns': [
                    r'/wp-login.php', r'/wp-admin/admin-ajax.php',
                    r'/xmlrpc.php', r'/wp-cron.php'
                ],
                'cookie_patterns': [
                    r'wordpress_', r'wp-settings'
                ]
            },
            'Joomla': {
                'html_patterns': [
                    r'joomla', r'/media/joomla/', r'/templates/',
                    r'index.php?option=com_', r'com_', r'mod_mainmenu'
                ],
                'meta_patterns': [
                    r'<meta name="generator" content="Joomla',
                    r'joomla.org'
                ],
                'header_patterns': [
                    r'x-joomla'
                ],
                'file_patterns': [
                    r'/administrator/', r'/components/',
                    r'/modules/', r'/plugins/'
                ],
                'cookie_patterns': [
                    r'joomla_'
                ]
            },
            'Drupal': {
                'html_patterns': [
                    r'drupal', r'sites/all/', r'sites/default/',
                    r'/misc/drupal.js', r'Drupal.settings'
                ],
                'meta_patterns': [
                    r'<meta name="Generator" content="Drupal',
                    r'Drupal.org'
                ],
                'header_patterns': [
                    r'x-drupal', r'x-generator: drupal'
                ],
                'file_patterns': [
                    r'/sites/default/files/', r'/modules/',
                    r'/themes/', r'/profiles/'
                ],
                'cookie_patterns': [
                    r'drupal_', r'SESS'
                ]
            },
            'Magento': {
                'html_patterns': [
                    r'magento', r'static/version', r'Mage.Cookies',
                    r'/static/frontend/', r'/static/adminhtml/'
                ],
                'meta_patterns': [
                    r'<meta name="generator" content="Magento',
                    r'Magento_'
                ],
                'header_patterns': [
                    r'x-magento', r'mage-cache-storage'
                ],
                'file_patterns': [
                    r'/customer/account/login/', r'/admin/',
                    r'/media/catalog/product/'
                ],
                'cookie_patterns': [
                    r'mage-', r'frontend'
                ]
            },
            'Shopify': {
                'html_patterns': [
                    r'shopify', r'shopify.shop', r'cdn.shopify.com',
                    r'shopify.theme', r'window.Shopify'
                ],
                'meta_patterns': [
                    r'shopify-digital-wallet',
                    r'//cdn.shopify.com'
                ],
                'header_patterns': [
                    r'x-shopify', r'shopify-country'
                ],
                'file_patterns': [
                    r'/cart', r'/collections/', r'/products/',
                    r'/apps/shopify/'
                ],
                'cookie_patterns': [
                    r'_shopify_', r'_landing_page'
                ]
            },
            'PrestaShop': {
                'html_patterns': [
                    r'prestashop', r'prestashop.css', r'prestashop.js',
                    r'prestashop.cart'
                ],
                'meta_patterns': [
                    r'<meta name="generator" content="PrestaShop',
                    r'prestashop.com'
                ],
                'header_patterns': [
                    r'x-prestashop'
                ],
                'file_patterns': [
                    r'/admin/', r'/modules/', r'/themes/'
                ],
                'cookie_patterns': [
                    r'PrestaShop-'
                ]
            },
            'OpenCart': {
                'html_patterns': [
                    r'opencart', r'catalog/view/theme',
                    r'system/library/cart/', r'index.php?route='
                ],
                'meta_patterns': [
                    r'<meta name="generator" content="OpenCart',
                    r'opencart.com'
                ],
                'header_patterns': [
                    r'x-opencart'
                ],
                'file_patterns': [
                    r'/admin/index.php', r'/catalog/controller/',
                    r'/system/storage/'
                ],
                'cookie_patterns': [
                    r'OCSESSID'
                ]
            },
            'WooCommerce': {
                'html_patterns': [
                    r'woocommerce', r'wc-', r'woocommerce-layout',
                    r'woocommerce-no-js', r'add_to_cart'
                ],
                'meta_patterns': [
                    r'woocommerce_active'
                ],
                'header_patterns': [
                    r'x-wc-'
                ],
                'file_patterns': [
                    r'/wc-api/', r'/wp-content/plugins/woocommerce/'
                ],
                'cookie_patterns': [
                    r'woocommerce_', r'wp_woocommerce'
                ]
            },
            'Ghost': {
                'html_patterns': [
                    r'ghost', r'ghost.org', r'ghost-powered',
                    r'data-ghost'
                ],
                'meta_patterns': [
                    r'<meta name="generator" content="Ghost',
                    r'ghost.org'
                ],
                'header_patterns': [
                    r'x-ghost'
                ],
                'file_patterns': [
                    r'/ghost/', r'/content/images/'
                ],
                'cookie_patterns': [
                    r'ghost-admin-api-session'
                ]
            },
            'TYPO3': {
                'html_patterns': [
                    r'typo3', r'TYPO3', r'typo3conf',
                    r'typo3temp', r'typo3/sysext'
                ],
                'meta_patterns': [
                    r'<meta name="generator" content="TYPO3',
                    r'TYPO3 CMS'
                ],
                'header_patterns': [
                    r'x-typo3'
                ],
                'file_patterns': [
                    r'/typo3/', r'/typo3conf/'
                ],
                'cookie_patterns': [
                    r'fe_typo_user'
                ]
            }
        }
        
        self.framework_patterns = {
            'React': {
                'html_patterns': [
                    r'react', r'React', r'__NEXT_DATA__',
                    r'_next/static', r'ReactDOM', r'react-root',
                    r'data-react'
                ],
                'meta_patterns': [
                    r'react-helmet', r'next/data'
                ],
                'script_patterns': [
                    r'react.', r'react-dom.', r'next.'
                ]
            },
            'Vue.js': {
                'html_patterns': [
                    r'vue', r'Vue', r'__vue__', r'v-',
                    r'v-model', r'v-bind', r'v-for',
                    r'vue-router', r'vuex'
                ],
                'meta_patterns': [
                    r'vue-meta'
                ],
                'script_patterns': [
                    r'vue.', r'vue-router.', r'vuex.'
                ]
            },
            'Angular': {
                'html_patterns': [
                    r'angular', r'ng-', r'data-ng',
                    r'ng-app', r'ng-controller', r'ng-model'
                ],
                'meta_patterns': [
                    r'angular'
                ],
                'script_patterns': [
                    r'angular.', r'@angular/'
                ]
            },
            'Django': {
                'html_patterns': [
                    r'csrfmiddlewaretoken', r'django',
                    r'Django', r'admin/css/'
                ],
                'meta_patterns': [
                    r'django'
                ],
                'header_patterns': [
                    r'server: WSGIServer', r'x-frame-options: DENY'
                ],
                'cookie_patterns': [
                    r'csrftoken', r'sessionid'
                ]
            },
            'Laravel': {
                'html_patterns': [
                    r'laravel', r'csrf-token',
                    r'XSRF-TOKEN', r'mix/manifest.json'
                ],
                'meta_patterns': [
                    r'laravel'
                ],
                'header_patterns': [
                    r'x-powered-by: laravel'
                ],
                'cookie_patterns': [
                    r'laravel_session', r'XSRF-TOKEN'
                ]
            },
            'Ruby on Rails': {
                'html_patterns': [
                    r'rails', r'csrf-param', r'csrf-token',
                    r'data-rails', r'rails-'
                ],
                'meta_patterns': [
                    r'rails'
                ],
                'header_patterns': [
                    r'x-rails', r'x-runtime: ruby'
                ],
                'cookie_patterns': [
                    r'_rails_session'
                ]
            },
            'Express.js': {
                'html_patterns': [
                    r'express'
                ],
                'header_patterns': [
                    r'x-powered-by: express'
                ],
                'cookie_patterns': [
                    r'connect.sid'
                ]
            },
            'ASP.NET': {
                'html_patterns': [
                    r'asp.net', r'__VIEWSTATE',
                    r'__EVENTVALIDATION', r'WebResource.axd'
                ],
                'meta_patterns': [
                    r'asp.net'
                ],
                'header_patterns': [
                    r'x-aspnet-version', r'x-aspnetmvc-version'
                ],
                'cookie_patterns': [
                    r'ASP.NET_SessionId'
                ]
            },
            'Flask': {
                'html_patterns': [
                    r'flask'
                ],
                'header_patterns': [
                    r'server: Werkzeug'
                ],
                'cookie_patterns': [
                    r'session'
                ]
            },
            'Spring Boot': {
                'html_patterns': [
                    r'spring', r'thymeleaf'
                ],
                'header_patterns': [
                    r'x-application-context'
                ],
                'cookie_patterns': [
                    r'JSESSIONID'
                ]
            }
        }

    def detect_cms_frameworks(self, target: str, port: int = 80, 
                            html_content: str = '', 
                            headers: Dict[str, str] = None,
                            use_ssl: bool = False) -> Dict[str, List[Dict]]:
        cache_key = f"{target}:{port}:{use_ssl}"
        if cache_key in self.detection_cache:
            return self.detection_cache[cache_key]
        
        results = {
            'cms': [],
            'frameworks': []
        }
        
        if not html_content:
            html_content, headers = self._fetch_web_content(target, port, use_ssl)
        
        cms_detections = self._detect_cms(html_content, headers)
        results['cms'] = cms_detections
        

        framework_detections = self._detect_frameworks(html_content, headers)
        results['frameworks'] = framework_detections
        
        self.detection_cache[cache_key] = results
        return results

    def _fetch_web_content(self, target: str, port: int, use_ssl: bool) -> Tuple[str, Dict]:
        protocol = "https" if use_ssl else "http"
        url = f"{protocol}://{target}:{port}/"
        
        try:
            response = requests.get(
                url, 
                timeout=self.timeout,
                headers={'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'},
                verify=False
            )
            return response.text, dict(response.headers)
        except Exception:
            return "", {}

    def _detect_cms(self, html_content: str, headers: Dict[str, str]) -> List[Dict]:
        detections = []
        
        for cms_name, patterns in self.cms_patterns.items():
            confidence = 0
            evidence = []
            
            for pattern in patterns.get('html_patterns', []):
                if re.search(pattern, html_content, re.IGNORECASE):
                    confidence += 20
                    evidence.append(f"HTML pattern: {pattern}")
            
            for pattern in patterns.get('meta_patterns', []):
                if re.search(pattern, html_content, re.IGNORECASE):
                    confidence += 25
                    evidence.append(f"Meta pattern: {pattern}")
            
            if headers:
                for header_name, header_value in headers.items():
                    header_string = f"{header_name}: {header_value}"
                    for pattern in patterns.get('header_patterns', []):
                        if re.search(pattern, header_string, re.IGNORECASE):
                            confidence += 15
                            evidence.append(f"Header pattern: {pattern}")
            

            if headers and 'set-cookie' in headers:
                for pattern in patterns.get('cookie_patterns', []):
                    if re.search(pattern, headers['set-cookie'], re.IGNORECASE):
                        confidence += 20
                        evidence.append(f"Cookie pattern: {pattern}")
            
            if confidence >= 30:  
                detections.append({
                    'name': cms_name,
                    'confidence': min(confidence, 100),
                    'evidence': evidence[:5]  
                })
        
        return sorted(detections, key=lambda x: x['confidence'], reverse=True)

    def _detect_frameworks(self, html_content: str, headers: Dict[str, str]) -> List[Dict]:
        detections = []
        
        for framework_name, patterns in self.framework_patterns.items():
            confidence = 0
            evidence = []
            
            for pattern in patterns.get('html_patterns', []):
                if re.search(pattern, html_content, re.IGNORECASE):
                    confidence += 20
                    evidence.append(f"HTML pattern: {pattern}")
            
            for pattern in patterns.get('meta_patterns', []):
                if re.search(pattern, html_content, re.IGNORECASE):
                    confidence += 25
                    evidence.append(f"Meta pattern: {pattern}")
            
            for pattern in patterns.get('script_patterns', []):
                if re.search(pattern, html_content, re.IGNORECASE):
                    confidence += 15
                    evidence.append(f"Script pattern: {pattern}")
            
            if headers:
                for header_name, header_value in headers.items():
                    header_string = f"{header_name}: {header_value}"
                    for pattern in patterns.get('header_patterns', []):
                        if re.search(pattern, header_string, re.IGNORECASE):
                            confidence += 15
                            evidence.append(f"Header pattern: {pattern}")
            
            if headers and 'set-cookie' in headers:
                for pattern in patterns.get('cookie_patterns', []):
                    if re.search(pattern, headers['set-cookie'], re.IGNORECASE):
                        confidence += 20
                        evidence.append(f"Cookie pattern: {pattern}")
            
            if confidence >= 25:  
                detections.append({
                    'name': framework_name,
                    'confidence': min(confidence, 100),
                    'evidence': evidence[:5]  
                })
        
        return sorted(detections, key=lambda x: x['confidence'], reverse=True)

    def deep_scan_cms(self, target: str, port: int = 80, use_ssl: bool = False) -> Dict:
        protocol = "https" if use_ssl else "http"
        base_url = f"{protocol}://{target}:{port}"
        
        results = {
            'cms': [],
            'admin_panels': [],
            'version_info': {},
            'vulnerability_hints': []
        }
        
        try:
            admin_paths = [
                '/wp-admin/', '/administrator/', '/admin/', 
                '/user/login', '/login', '/backend/',
                '/typo3/', '/ghost/', '/studio/'
            ]
            
            for path in admin_paths:
                try:
                    admin_url = urljoin(base_url, path)
                    response = requests.head(admin_url, timeout=3, verify=False)
                    if response.status_code in [200, 301, 302]:
                        results['admin_panels'].append({
                            'path': path,
                            'status_code': response.status_code,
                            'url': admin_url
                        })
                except:
                    continue
            
            version_files = [
                '/readme.html', '/CHANGELOG.txt', '/RELEASE_NOTES.txt',
                '/wp-includes/version.php', '/misc/drupal.js'
            ]
            
            for file_path in version_files:
                try:
                    file_url = urljoin(base_url, file_path)
                    response = requests.get(file_url, timeout=3, verify=False)
                    if response.status_code == 200:
                        version = self._extract_version_from_content(response.text, file_path)
                        if version:
                            results['version_info'][file_path] = version
                except:
                    continue
        
        except Exception as e:
            pass
        
        return results

    def _extract_version_from_content(self, content: str, file_path: str) -> Optional[str]:
        version_patterns = [
            r'Version\s*:\s*([\d.]+)',
            r'version\s*=\s*[\'"]([\d.]+)[\'"]',
            r'v([\d.]+)',
            r'(\d+\.\d+(?:\.\d+)?)'
        ]
        
        for pattern in version_patterns:
            match = re.search(pattern, content, re.IGNORECASE)
            if match:
                return match.group(1)
        
        return None

    def get_cms_info(self, cms_name: str) -> Dict[str, str]:
        cms_info = {
            'WordPress': {
                'description': 'Most popular content management system',
                'website': 'https://wordpress.org',
                'language': 'PHP',
                'default_ports': [80, 443]
            },
            'Joomla': {
                'description': 'Open source content management system',
                'website': 'https://joomla.org',
                'language': 'PHP',
                'default_ports': [80, 443]
            },
            'Drupal': {
                'description': 'Enterprise content management platform',
                'website': 'https://drupal.org',
                'language': 'PHP',
                'default_ports': [80, 443]
            },
            'Magento': {
                'description': 'E-commerce platform',
                'website': 'https://magento.com',
                'language': 'PHP',
                'default_ports': [80, 443]
            },
            'Shopify': {
                'description': 'Cloud-based e-commerce platform',
                'website': 'https://shopify.com',
                'language': 'Liquid',
                'default_ports': [80, 443]
            }
        }
        
        return cms_info.get(cms_name, {
            'description': 'No information available',
            'website': '',
            'language': 'Unknown',
            'default_ports': []
        })

    def get_framework_info(self, framework_name: str) -> Dict[str, str]:
        framework_info = {
            'React': {
                'description': 'JavaScript library for building user interfaces',
                'website': 'https://reactjs.org',
                'language': 'JavaScript',
                'type': 'Frontend'
            },
            'Vue.js': {
                'description': 'Progressive JavaScript framework',
                'website': 'https://vuejs.org',
                'language': 'JavaScript',
                'type': 'Frontend'
            },
            'Angular': {
                'description': 'Platform for building mobile and desktop web applications',
                'website': 'https://angular.io',
                'language': 'TypeScript',
                'type': 'Frontend'
            },
            'Django': {
                'description': 'High-level Python web framework',
                'website': 'https://djangoproject.com',
                'language': 'Python',
                'type': 'Backend'
            },
            'Laravel': {
                'description': 'PHP web application framework',
                'website': 'https://laravel.com',
                'language': 'PHP',
                'type': 'Backend'
            }
        }
        
        return framework_info.get(framework_name, {
            'description': 'No information available',
            'website': '',
            'language': 'Unknown',
            'type': 'Unknown'
        })

    def clear_cache(self):
        self.detection_cache.clear()

    def get_detection_stats(self) -> Dict[str, int]:
        return {
            'cms_count': len(self.cms_patterns),
            'framework_count': len(self.framework_patterns),
            'cache_size': len(self.detection_cache)
        }

def quick_cms_detect(target: str, port: int = 80, use_ssl: bool = False) -> Dict:   
    detector = CMSFrameworkDetector()
    return detector.detect_cms_frameworks(target, port, use_ssl=use_ssl)