from typing import List, Dict, Any
from datetime import datetime

class HTMLReportGenerator:
    def __init__(self):
        self.css = self._get_css()
    
    def _get_css(self) -> str:
        return """
        <style>
            * { margin: 0; padding: 0; box-sizing: border-box; }
            body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background: #f5f5f5; padding: 20px; }
            .container { max-width: 1400px; margin: 0 auto; }
            .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 30px; border-radius: 10px; margin-bottom: 30px; }
            .header h1 { font-size: 2.5em; margin-bottom: 10px; }
            .header p { opacity: 0.9; font-size: 1.1em; }
            .stats { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 20px; margin-bottom: 30px; }
            .stat-card { background: white; padding: 20px; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
            .stat-card h3 { color: #666; font-size: 0.9em; margin-bottom: 10px; }
            .stat-card .value { font-size: 2em; font-weight: bold; color: #333; }
            .stat-card.critical .value { color: #dc3545; }
            .stat-card.high .value { color: #fd7e14; }
            .stat-card.medium .value { color: #ffc107; }
            .stat-card.low .value { color: #28a745; }
            .section { background: white; padding: 25px; border-radius: 10px; margin-bottom: 20px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
            .section h2 { color: #333; margin-bottom: 20px; border-bottom: 2px solid #667eea; padding-bottom: 10px; }
            table { width: 100%; border-collapse: collapse; }
            th { background: #667eea; color: white; padding: 12px; text-align: left; }
            td { padding: 12px; border-bottom: 1px solid #ddd; }
            tr:hover { background: #f8f9fa; }
            .badge { padding: 4px 8px; border-radius: 4px; font-size: 0.85em; font-weight: bold; }
            .badge-critical { background: #dc3545; color: white; }
            .badge-high { background: #fd7e14; color: white; }
            .badge-medium { background: #ffc107; color: #333; }
            .badge-low { background: #28a745; color: white; }
            .badge-secure { background: #17a2b8; color: white; }
            .vuln-card { border-left: 4px solid #dc3545; padding: 15px; margin-bottom: 15px; background: #f8f9fa; border-radius: 5px; }
            .vuln-card.high { border-left-color: #fd7e14; }
            .vuln-card.medium { border-left-color: #ffc107; }
            .vuln-card.low { border-left-color: #28a745; }
            .vuln-card h4 { margin-bottom: 10px; color: #333; }
            .vuln-card p { color: #666; margin-bottom: 8px; }
            .vuln-card .meta { font-size: 0.9em; color: #999; }
            .tech-tag { display: inline-block; background: #667eea; color: white; padding: 4px 10px; border-radius: 15px; margin: 3px; font-size: 0.9em; }
            .footer { text-align: center; padding: 20px; color: #666; font-size: 0.9em; }
        </style>
        """
    
    def generate(self, scan_data: Dict[str, Any], output_path: str):
        html = f"""
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Xikomap Security Scan Report</title>
            {self.css}
        </head>
        <body>
            <div class="container">
                <div class="header">
                    <h1>🔒 Xikomap Security Scan Report</h1>
                    <p>Target: {scan_data.get('target', 'N/A')} | Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
                </div>
                
                {self._generate_stats(scan_data)}
                {self._generate_ports_section(scan_data)}
                {self._generate_vulnerabilities_section(scan_data)}
                {self._generate_misconfigurations_section(scan_data)}
                {self._generate_technologies_section(scan_data)}
                {self._generate_ssl_section(scan_data)}
                
                <div class="footer">
                    <p>Generated by Xikomap v{scan_data.get('version', '2.3.0')} | Scan Duration: {scan_data.get('duration', 'N/A')}s</p>
                </div>
            </div>
        </body>
        </html>
        """
        
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(html)
    
    def _generate_stats(self, data: Dict[str, Any]) -> str:
        ports = data.get('ports', [])
        vulns = data.get('vulnerabilities', [])
        misconfigs = data.get('misconfigurations', [])
        
        critical = sum(1 for v in vulns if v.get('severity') == 'critical')
        high = sum(1 for v in vulns if v.get('severity') == 'high')
        medium = sum(1 for v in vulns if v.get('severity') == 'medium')
        
        return f"""
        <div class="stats">
            <div class="stat-card">
                <h3>Open Ports</h3>
                <div class="value">{len(ports)}</div>
            </div>
            <div class="stat-card critical">
                <h3>Critical Issues</h3>
                <div class="value">{critical}</div>
            </div>
            <div class="stat-card high">
                <h3>High Risk</h3>
                <div class="value">{high}</div>
            </div>
            <div class="stat-card medium">
                <h3>Medium Risk</h3>
                <div class="value">{medium}</div>
            </div>
            <div class="stat-card">
                <h3>Misconfigurations</h3>
                <div class="value">{len(misconfigs)}</div>
            </div>
        </div>
        """
    
    def _generate_ports_section(self, data: Dict[str, Any]) -> str:
        ports = data.get('ports', [])
        
        rows = ""
        for port in ports:
            risk_badge = self._get_risk_badge(port.get('risk_level', 'low'))
            rows += f"""
            <tr>
                <td>{port.get('ip', 'N/A')}</td>
                <td>{port.get('port', 'N/A')}</td>
                <td>{port.get('protocol', 'N/A')}</td>
                <td>{port.get('service', 'N/A')}</td>
                <td>{risk_badge}</td>
                <td>{port.get('banner', 'N/A')[:50]}</td>
            </tr>
            """
        
        return f"""
        <div class="section">
            <h2>📡 Open Ports</h2>
            <table>
                <thead>
                    <tr>
                        <th>IP Address</th>
                        <th>Port</th>
                        <th>Protocol</th>
                        <th>Service</th>
                        <th>Risk</th>
                        <th>Banner</th>
                    </tr>
                </thead>
                <tbody>
                    {rows}
                </tbody>
            </table>
        </div>
        """
    
    def _generate_vulnerabilities_section(self, data: Dict[str, Any]) -> str:
        vulns = data.get('vulnerabilities', [])
        
        if not vulns:
            return """
            <div class="section">
                <h2>🛡️ Vulnerabilities</h2>
                <p>No vulnerabilities detected. Great job!</p>
            </div>
            """
        
        vuln_cards = ""
        for vuln in vulns:
            severity = vuln.get('severity', 'medium')
            vuln_cards += f"""
            <div class="vuln-card {severity}">
                <h4>{vuln.get('cve_id', 'N/A')} - {vuln.get('title', 'N/A')}</h4>
                <p>{vuln.get('description', 'N/A')}</p>
                <div class="meta">
                    <strong>CVSS:</strong> {vuln.get('cvss_score', 'N/A')} | 
                    <strong>Service:</strong> {vuln.get('affected_service', 'N/A')} | 
                    <strong>Fix:</strong> {vuln.get('fix_version', 'N/A')}
                </div>
            </div>
            """
        
        return f"""
        <div class="section">
            <h2>️ Vulnerabilities ({len(vulns)} found)</h2>
            {vuln_cards}
        </div>
        """
    
    def _generate_misconfigurations_section(self, data: Dict[str, Any]) -> str:
        misconfigs = data.get('misconfigurations', [])
        
        if not misconfigs:
            return """
            <div class="section">
                <h2>️ Misconfigurations</h2>
                <p>No misconfigurations detected.</p>
            </div>
            """
        
        rows = ""
        for mc in misconfigs:
            badge = f'<span class="badge badge-{mc.get("severity", "low")}">{mc.get("severity", "N/A").upper()}</span>'
            rows += f"""
            <tr>
                <td>{badge}</td>
                <td>{mc.get('type', 'N/A')}</td>
                <td>{mc.get('description', 'N/A')}</td>
                <td>{mc.get('port', 'N/A')}</td>
                <td>{mc.get('recommendation', 'N/A')}</td>
            </tr>
            """
        
        return f"""
        <div class="section">
            <h2>⚙️ Misconfigurations ({len(misconfigs)} found)</h2>
            <table>
                <thead>
                    <tr>
                        <th>Severity</th>
                        <th>Type</th>
                        <th>Description</th>
                        <th>Port</th>
                        <th>Recommendation</th>
                    </tr>
                </thead>
                <tbody>
                    {rows}
                </tbody>
            </table>
        </div>
        """
    
    def _generate_technologies_section(self, data: Dict[str, Any]) -> str:
        techs = data.get('technologies', [])
        
        if not techs:
            return """
            <div class="section">
                <h2>🔧 Detected Technologies</h2>
                <p>No technologies detected.</p>
            </div>
            """
        
        tags = " ".join([f'<span class="tech-tag">{t}</span>' for t in techs])
        
        return f"""
        <div class="section">
            <h2> Detected Technologies ({len(techs)} found)</h2>
            <div style="margin-top: 15px;">
                {tags}
            </div>
        </div>
        """
    
    def _generate_ssl_section(self, data: Dict[str, Any]) -> str:
        ssl = data.get('ssl_analysis', {})
        
        if not ssl:
            return ""
        
        risk_badge = self._get_risk_badge(ssl.get('risk_level', 'medium'))
        
        return f"""
        <div class="section">
            <h2>🔐 SSL/TLS Analysis</h2>
            <p><strong>Risk Level:</strong> {risk_badge}</p>
            <p><strong>Protocols:</strong> {', '.join(ssl.get('protocols', []))}</p>
            <p><strong>Weak Protocols:</strong> {', '.join(ssl.get('weak_protocols', ['None']))}</p>
            <h3 style="margin-top: 20px;">Recommendations:</h3>
            <ul style="margin-left: 20px; margin-top: 10px;">
                {''.join([f'<li>{rec}</li>' for rec in ssl.get('recommendations', [])])}
            </ul>
        </div>
        """
    
    def _get_risk_badge(self, risk: str) -> str:
        return f'<span class="badge badge-{risk}">{risk.upper()}</span>'